# Generated by Django 5.0.7 on 2024-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=30),
            preserve_default=False,
        ),
    ]
