# Generated by Django 5.0.7 on 2024-07-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
